default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: rake_tasks

test:
  <<: *default
  database: rake_tasks_test

production:
  <<: *default
  database: rake_tasks_pro
